Project Library: library-feature
PhillipUg/library pull request #3
Opened 2020-08-12 13:00 UTC by PhillipUg

In the following project we have done the following:
 - built a simple library app with Javascript, HTML & CSS
 - we enabled users to add books, remove books and change their state from either read or unread
- we implemented a simple form to help users add books

2020-08-12 23:19 UTC, rOluochKe requested changes
Hello @PhillipUg and @SafaErden 
### You have done well so far :clap: However, you have an issue to fix:-
- [ ] Separate you dom from application logic
- [ ] You are also required to store the book object in an array, see the image below
![array-book](https://user-images.githubusercontent.com/8114528/90077654-5d6c9f80-dd0b-11ea-808a-c24f217fc62b.png)
### Make the change and submit for another code review.
- Happy coding!

By Raymond
Slack @iamraymond

2020-08-12 23:20 UTC, rOluochKe commented on app.js
> +}
### separate dom from the logic

2020-08-12 23:22 UTC, rOluochKe commented on app.js
> +const add = document.getElementById('add');
### Separate dom from logic

2020-08-14 06:04 UTC, uche-inyama approved these changes
# Approved

## Hi team :clap: 

This project is approved :100: 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-08-14 08:27 UTC, merged